fix:[#2398] Support Bots that use Single Tenant AAD Applications
southworkscom/BotFramework-Emulator pull request #98
Opened 2024-03-18 15:05 UTC by JhontSouth

Fixes # 2398

## Description
This PR adds the support to use the _**tenant id**_ value to authenticate Emulator into Single Tenant apps.
This feature requires bots with the las updates of botbuilder-dotnet and botbuilder-js:
PR # 321
PR # 123

## Specific Changes
  - Added **_tenantId_** property to the classes involved in authentication.
  - Added support to obtain access token through Single Tenant login endpoint.
  - Added method to use tenant id value to create a dynamic _**issuer**_.

## Testing
These images show the new field Tenant ID in the Open Bot and New Bot Configuration views. 
![image](https://github.com/southworks/BotFramework-Emulator/assets/122501764/76aad453-b6bc-4085-b234-17cd00bb85d6)
![image](https://github.com/southworks/BotFramework-Emulator/assets/122501764/476583cb-7e67-482c-8498-436015263263)

This is the new message error related to authentication.
![image](https://github.com/southworks/BotFramework-Emulator/assets/122501764/db00b5d0-9aff-47f8-ab39-c1556860f633)

The following image shows the Emulator working with a bot using Single Tenant authentication.
![image](https://github.com/southworks/botbuilder-dotnet/assets/122501764/cb8727f8-e76c-4942-830c-1ceae9eafb95)

2024-03-18 20:55 UTC, ceciliaavila requested changes
- Add the issue number in the title and description of the issue (don't link it to the SW PR).
- Add more evidence in the testing section. How the new text field looks in the updated views, How the new error message looks like.

2024-03-18 20:55 UTC, ceciliaavila commented on packages/app/main/src/server/state/botEndpoint.ts
> +
I'm not sure about this. Could it be a government credential also a Single Tenant app?

2024-03-18 20:55 UTC, ceciliaavila commented on packages/sdk/shared/src/types/botEndpoint.ts
> +  tenantId: string;
Should this be optional?
```suggestion
  tenantId?: string;
```

2024-03-20 18:06 UTC, JhontSouth commented on packages/app/main/src/server/state/botEndpoint.ts
> +
probably, but the issue is that there is no info about the url endpoint that we could use

2024-03-20 18:12 UTC, JhontSouth commented on packages/app/main/src/server/state/botEndpoint.ts
> +
Check this class https://github.com/southworks/botbuilder-js/blob/0108ac2f7d9f36d3c9315ffabdc2b7c7babce191/libraries/botframework-connector/src/auth/governmentConstants.ts

2024-03-21 12:54 UTC, sw-joelmut requested changes

2024-03-21 12:54 UTC, sw-joelmut commented on packages/sdk/shared/src/emulatorApi/conversationService.ts
> +  tenantId?: string;
shouldnt this be `msaTenantId` ?

2024-03-21 12:54 UTC, sw-joelmut commented on packages/sdk/shared/src/types/botEndpoint.ts
> +  tenantId: string;
shouldnt this be `msaTenantId`?

2024-03-22 16:01 UTC, JhontSouth commented on packages/sdk/shared/src/types/botEndpoint.ts
> +  tenantId: string;
fixed and tested 
![image](https://github.com/southworks/BotFramework-Emulator/assets/122501764/4d950280-6e99-4d35-8902-bd40f15a9703)

2024-04-03 13:25 UTC, JhontSouth commented
@ceciliaavila @sw-joelmut 
The feedback is applied
Tracy's answer about the gov auth with ST is pending

2024-04-03 15:45 UTC, sw-joelmut approved these changes

2024-04-03 17:36 UTC, ceciliaavila approved these changes

2024-04-05 14:07 UTC, ceciliaavila commented
/promoted 2457

2024-04-05 14:07 UTC, closed without merging